edit_uri: https://github.com/tbnobody/OpenDTU-docs/edit/master/docs/

repo_url: https://github.com/tbnobody/OpenDTU
repo_name: tbnobody/OpenDTU

site_name: OpenDTU Documentation
site_description: Open Source software for ESP32 MCUs to talk to Hoymiles Inverters
site_author: "Thomas Basler"
copyright: Copyright &copy; 2022 - 2024 Thomas Basler and others

extra:
  social:
    - icon: material/github
      link: https://github.com/tbnobody/OpenDTU/discussions
      name: GitHub Discussions
    - icon: fontawesome/brands/discord
      link: https://discord.gg/WzhxEY62mB
      name: Discord Chat
    - name: Donate
      link: https://ko-fi.com/tbnobody
      icon: octicons/heart-fill-24

theme:
  logo: assets/images/logo.png
  favicon: favicon.ico
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

  features:
    ## Setting up navigation
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.follow
    ## Search
    - navigation.path
    - search.suggest
    ## Content tabs
    - content.tooltips
    - content.action.edit
    - content.action.view

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - assets/javascript/tablesort.js

plugins:
  - search
  - glightbox
  - git-revision-date-localized:
      type: datetime
      timezone: Europe/Berlin
      enable_creation_date: true

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true

# Page tree
nav:
  - Home:
      - index.md
      - Hardware Support: hardware/index.md
      - Firmware Installation: firmware/index.md
      - Troubleshooting: troubleshooting.md
  - Hardware:
      - hardware/index.md
      - hardware/inverter_overview.md
      - ESP32 Modules:
        - hardware/esp32nodemcu_38pin.md
        - hardware/olimexpoeiso.md
      - RF Modules:
        - hardware/nrf24l01plus.md
        - hardware/cmt2300a.md
      - hardware/led.md
      - hardware/display.md
  - Firmware:
    - Installation:
      - firmware/index.md
      - firmware/flash_esp.md
      - firmware/webinstall.md
    - firmware/wifi_setup.md
    - Web UI:
      - firmware/configuration/login.md
      - Live View:
        - firmware/configuration/live_view.md
        - firmware/configuration/live_view_info.md
        - firmware/configuration/live_view_eventlog.md
        - firmware/configuration/live_view_power.md
        - firmware/configuration/live_view_limit.md
        - firmware/configuration/live_view_gridprofile.md
      - Settings:
        - firmware/configuration/network_settings.md
        - firmware/configuration/ntp_settings.md
        - firmware/configuration/mqtt_settings.md
        - firmware/configuration/inverter_settings.md
        - firmware/configuration/security_settings.md
        - firmware/configuration/dtu_settings.md
        - firmware/configuration/device_settings.md
        - firmware/configuration/config_settings.md
        - firmware/configuration/firmware_upgrade.md
        - firmware/configuration/device_reboot.md
      - Info:
        - firmware/configuration/system_info.md
        - firmware/configuration/network_info.md
        - firmware/configuration/ntp_info.md
        - firmware/configuration/mqtt_info.md
        - firmware/configuration/console.md
      - firmware/configuration/about.md
    - firmware/update.md
    - firmware/device_profiles.md
    - firmware/mqtt_topics.md
    - firmware/web_api.md
    - firmware/faq.md
    - Howtos:
      - firmware/howto/serial_console.md
      - firmware/howto/migrate_generic.md
      - firmware/howto/upgrade_partition.md
      - firmware/howto/generate_image.md
    - Compiling:
      - firmware/compile_vscode.md
      - firmware/compile_cli.md
      - firmware/compile_webapp.md
    - License: license.md
  - 3rd Party:
      - 3rd_party/blinkyparts.md
      - 3rd_party/opendtu_fusion.md
      - 3rd_party/related.md
      - 3rd_party/cases.md
      - 3rd_party/pcb.md
